name: Debug APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Init language submodule only
        run: git submodule update --init external/language || true
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
      - name: Flutter pub get
        run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: namida-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error